# Generated by Django 5.2.7 on 2025-10-22 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Converts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fullname", models.CharField(max_length=120)),
                ("Email", models.EmailField(blank=True, max_length=254, null=True)),
                ("Phone_number", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=150)),
                ("Prayer_point", models.CharField(max_length=300)),
                ("date", models.DateField(default=datetime.date(2025, 10, 22))),
            ],
            options={
                "verbose_name_plural": "Converts",
            },
        ),
    ]
