# Generated by Django 4.2.7 on 2024-02-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Converts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=120)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone_number', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=150)),
                ('Prayer_point', models.CharField(max_length=300)),
            ],
        ),
    ]
