# Generated by Django 5.2.7 on 2026-01-08 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="converts",
            name="date",
            field=models.DateField(default=datetime.date(2026, 1, 8)),
        ),
    ]
