# Generated by Django 4.2.7 on 2024-03-21 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='converts',
            options={'verbose_name_plural': 'Converts'},
        ),
        migrations.AddField(
            model_name='converts',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 1, 25, 39, 414117)),
        ),
    ]
