# Generated by Django 4.2.7 on 2024-03-21 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_converts_options_converts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converts',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 21)),
        ),
    ]
